# Generated by Django 4.2.23 on 2025-12-08 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0009_order_offer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(default="UZS", max_length=10)),
                ("confirmed_by_customer", models.BooleanField(default=False)),
                ("confirmed_by_carrier", models.BooleanField(default=False)),
                (
                    "external_transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("cash", "Наличные"), ("bank_transfer", "Перечисление")],
                        default="cash",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Создано"),
                            ("CONFIRMED_BY_CUSTOMER", "Оплачено заказчиком"),
                            ("CONFIRMED_BY_CARRIER", "Получено перевозчиком"),
                            ("COMPLETED", "Завершено"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
