# Generated by Django 4.2.23 on 2025-12-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="confirmed_by_logistic",
            field=models.BooleanField(default=False),
        ),
    ]
