# Generated by Django 4.2.23 on 2025-12-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_payment_confirmed_by_logistic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличные"),
                    ("bank_transfer", "Перечисление"),
                    ("both", "Наличные + перечисление"),
                ],
                default="cash",
                max_length=32,
            ),
        ),
    ]
