name: PROD
values:
  - key: base_url
    value: ''
    enabled: true
  - key: access_token
    value: ''
    enabled: true
  - key: refresh_token
    value: ''
    enabled: true
  - key: user_id
    value: ''
    enabled: true
  - key: order_id
    value: ''
    enabled: true
  - key: offer_id
    value: ''
    enabled: true
  - key: cargo_uuid
    value: ''
    enabled: true
  - key: payment_id
    value: ''
    enabled: true
  - key: agreement_id
    value: ''
    enabled: true
  - key: rating_id
    value: ''
    enabled: true
  - key: rating_user_id
    value: ''
    enabled: true
  - key: invite_token
    value: ''
    enabled: true
  - key: share_token
    value: ''
    enabled: true
  - key: city_query
    value: ''
    enabled: true
  - key: country_query
    value: ''
    enabled: true
