# Generated by Django 4.2.23 on 2025-11-26 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_remove_orderdocument_orderdoc_order_idx_and_more"),
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrating",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="orders.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AddIndex(
            model_name="userrating",
            index=models.Index(fields=["score"], name="ratings_use_score_1dd2b7_idx"),
        ),
    ]
