# Generated by Django 4.2.23 on 2026-01-29 11:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0018_order_driver_currency_order_driver_payment_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ratings", "0002_alter_userrating_order_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userrating",
            unique_together={("rated_by", "rated_user", "order")},
        ),
    ]
