# Generated by Django 4.2.23 on 2025-11-13 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_alter_order_options_alter_orderdocument_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('pending', 'В ожидании'), ('en_route', 'В пути'), ('delivered', 'Доставлен'), ('no_driver', 'Без водителя')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('pending', 'В ожидании'), ('en_route', 'В пути'), ('delivered', 'Доставлен'), ('no_driver', 'Без водителя')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Изменение статуса заказа',
                'verbose_name_plural': 'История статусов заказов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='orderdocument',
            name='category',
            field=models.CharField(choices=[('licenses', 'Лицензии'), ('contracts', 'Договора'), ('loading', 'Документы о погрузке'), ('unloading', 'Документы о разгрузке'), ('other', 'Дополнительно')], default='other', max_length=32),
        ),
        migrations.AddIndex(
            model_name='orderdocument',
            index=models.Index(fields=['category'], name='orderdoc_category_idx'),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['order'], name='orderstatus_order_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['created_at'], name='orderstatus_created_idx'),
        ),
    ]
