# Generated by Django 4.2.23 on 2025-11-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_orderstatushistory_orderdocument_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="driver_status",
            field=models.CharField(
                choices=[
                    ("stopped", "Остановился"),
                    ("en_route", "В пути"),
                    ("problem", "Проблема"),
                ],
                default="en_route",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В ожидании"),
                    ("en_route", "В пути"),
                    ("delivered", "Доставлен"),
                    ("no_driver", "Без водителя"),
                    ("paid", "Оплачено"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("pending", "В ожидании"),
                    ("en_route", "В пути"),
                    ("delivered", "Доставлен"),
                    ("no_driver", "Без водителя"),
                    ("paid", "Оплачено"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="old_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "В ожидании"),
                    ("en_route", "В пути"),
                    ("delivered", "Доставлен"),
                    ("no_driver", "Без водителя"),
                    ("paid", "Оплачено"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
