# Generated by Django 4.2.23 on 2025-11-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_alter_order_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="loading_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="unloading_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
