# Generated by Django 4.2.23 on 2025-11-26 12:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_order_created_by"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="orderdocument",
            name="orderdoc_order_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderdocument",
            name="orderdoc_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderdocument",
            name="orderdoc_uploader_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderdocument",
            name="orderdoc_category_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderstatushistory",
            name="orderstatus_order_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderstatushistory",
            name="orderstatus_created_idx",
        ),
    ]
