# Generated by Django 4.2.23 on 2025-11-29 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0004_alter_offer_price_value"),
        ("orders", "0008_remove_orderdocument_orderdoc_order_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="offer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order",
                to="offers.offer",
            ),
        ),
    ]
