# Generated by Django 4.2.23 on 2025-12-09 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0009_order_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invite_token",
            field=models.UUIDField(
                blank=True, help_text="Токен приглашения перевозчика", null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="invited_carrier",
            field=models.ForeignKey(
                blank=True,
                help_text="Перевозчик, приглашённый вручную по ID",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invited_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
