# Generated by Django 4.2.23 on 2025-12-09 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0010_order_invite_token_order_invited_carrier"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="logistic",
            field=models.ForeignKey(
                blank=True,
                help_text="Логист-посредник (экспедитор) по заказу",
                limit_choices_to={"role": "LOGISTIC"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logistic_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
