# Generated by Django 4.2.23 on 2025-12-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0012_alter_order_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="carrier_accepted_terms",
            field=models.BooleanField(
                default=False, verbose_name="Перевозчик/Водитель принял условия заказа"
            ),
        ),
    ]
