# Generated by Django 4.2.23 on 2025-12-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0013_order_carrier_accepted_terms"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("bank_transfer", "Перечисление")],
                default="cash",
                max_length=20,
            ),
        ),
    ]
