# Generated by Django 4.2.23 on 2026-01-21 06:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0015_alter_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="share_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Публичный токен для просмотра заказа",
                unique=True,
            ),
        ),
    ]
