# Generated by Django 4.2.23 on 2026-01-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0016_order_share_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="driver_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Сумма, которую получит водитель",
                max_digits=14,
                null=True,
            ),
        ),
    ]
