# Generated by Django 4.2.23 on 2026-01-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0017_order_driver_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="driver_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UZS", "сум"),
                    ("KZT", "тнг"),
                    ("RUB", "руб"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                ],
                help_text="Валюта выплаты водителю",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="driver_payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "Наличные"),
                    ("bank_transfer", "Перечисление"),
                    ("both", "Наличные + перечисление"),
                ],
                help_text="Метод оплаты водителю",
                max_length=20,
                null=True,
            ),
        ),
    ]
