# Generated by Django 4.2.23 on 2026-02-09 06:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0018_order_driver_currency_order_driver_payment_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
                ),
                ("city", models.CharField(blank=True, max_length=120)),
                ("country", models.CharField(blank=True, max_length=120)),
                ("recorded_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gps",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["recorded_at"], name="orders_driv_recorde_16f150_idx")
                ],
            },
        ),
    ]
