# Generated by Django 4.2.23 on 2026-02-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0019_driverlocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_hide_contacts",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="logistic_hide_contacts",
            field=models.BooleanField(default=False),
        ),
    ]
