# Generated by Django 4.2.23 on 2026-02-24 06:18

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0020_order_customer_hide_contacts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driverlocation",
            name="city",
        ),
        migrations.RemoveField(
            model_name="driverlocation",
            name="country",
        ),
        migrations.RemoveField(
            model_name="driverlocation",
            name="order",
        ),
        migrations.AddField(
            model_name="driverlocation",
            name="driver",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="driverlocation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        # 🔥 FIX GEOMETRY CAST
        migrations.RunSQL(
            sql="""
                ALTER TABLE orders_driverlocation
                ALTER
                COLUMN point TYPE geometry(Point,4326)
                USING point::geometry(Point,4326);
                """,
            reverse_sql="""
                        ALTER TABLE orders_driverlocation
                        ALTER
                        COLUMN point TYPE geometry(Point,4326);
                        """,
        ),
        migrations.AlterField(
            model_name="driverlocation",
            name="recorded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="driverlocation",
            index=models.Index(
                fields=["driver"],
                name="orders_driv_driver__45b272_idx",
            ),
        ),
    ]
