# Generated by Django 4.2.23 on 2026-02-24 06:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0021_remove_driverlocation_city_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE orders_driverlocation
                        ALTER COLUMN point TYPE geometry(Point,4326)
                        USING point::geometry(Point,4326);
                    """,
                    reverse_sql="""
                        ALTER TABLE orders_driverlocation
                        ALTER COLUMN point TYPE geography(Point,4326)
                        USING point::geography;
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="driverlocation",
                    name="point",
                    field=django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
        ),
    ]
