# Generated by Django 4.2.23 on 2026-02-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0022_alter_driverlocation_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverlocation",
            name="speed",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
