# Generated by Django 4.2.23 on 2026-03-30 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_message_attachment_message_attachment_content_type_and_more"),
        ("orders", "0023_driverlocation_speed"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="chat",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order",
                to="chat.chat",
            ),
        ),
    ]
