# Generated by Django 4.2.23 on 2025-11-08 08:03

import django.core.validators
from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geoplace',
            options={'ordering': ['country_code', 'name']},
        ),
        migrations.RenameIndex(
            model_name='geoplace',
            new_name='geoplace_cc_name_idx',
            old_name='geo_geoplac_country_b0a8e7_idx',
        ),
        migrations.AlterUniqueTogether(
            name='geoplace',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='geoplace',
            name='country_code',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', message='ISO-2 код страны, например UZ, KZ')]),
        ),
        migrations.AddIndex(
            model_name='geoplace',
            index=models.Index(django.db.models.functions.text.Lower('name'), name='geoplace_lower_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='geoplace',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('country_code'), name='uq_geoplace_lower_name_country_code'),
        ),
    ]
