# Generated by Django 4.2.23 on 2025-11-14 14:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0002_alter_geoplace_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geoplace",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
    ]
