# Generated by Django 4.2.23 on 2025-11-15 07:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0003_alter_geoplace_point"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE geo_geoplace
                        ALTER COLUMN point TYPE geometry(Point,4326)
                        USING point::geometry(Point,4326);
                    """,
                    reverse_sql="""
                        ALTER TABLE geo_geoplace
                        ALTER COLUMN point TYPE geography(Point,4326)
                        USING point::geography;
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="geoplace",
                    name="point",
                    field=django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
        ),
    ]
