# Generated by Django 4.2.23 on 2025-11-15 07:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0003_alter_geoplace_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geoplace",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
