# Generated by Django 4.2.23 on 2025-11-22 07:58

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_alter_geoplace_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoplace',
            name='name_latin',
            field=models.CharField(db_index=True, default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='geoplace',
            index=models.Index(django.db.models.functions.text.Lower('name_latin'), name='geoplace_lower_latin_idx'),
        ),
    ]
