# Generated by Django 4.2.23 on 2026-03-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0005_geoplace_name_latin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="geoplace",
            name="region",
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
