# Generated by Django 4.2.23 on 2026-03-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="allow_join_by_link",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chat",
            name="invite_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chat",
            name="invite_token",
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="chatparticipant",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
