# Generated by Django 4.2.23 on 2026-03-30 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0002_message_attachment_message_attachment_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatparticipant",
            name="invited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatparticipant",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_chat_invites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
