# Generated by Django 4.2.23 on 2025-08-29 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("loads", "0003_cargo_price_currency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "price_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "price_currency",
                    models.CharField(
                        choices=[
                            ("UZS", "сум"),
                            ("KZT", "тнг"),
                            ("RUB", "руб"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                        ],
                        default="UZS",
                        max_length=3,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("accepted_by_customer", models.BooleanField(default=False)),
                ("accepted_by_carrier", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="loads.cargo",
                    ),
                ),
                (
                    "carrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["cargo", "is_active"], name="offers_offe_cargo_i_1e0469_idx"
                    ),
                    models.Index(
                        fields=["carrier", "is_active"], name="offers_offe_carrier_ef582d_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.UniqueConstraint(
                fields=("cargo", "carrier"), name="uniq_offer_per_carrier_per_cargo"
            ),
        ),
    ]
