# Generated by Django 4.2.23 on 2025-09-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0002_remove_offer_uniq_offer_per_carrier_per_cargo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="initiator",
            field=models.CharField(
                choices=[("CUSTOMER", "Заказчик"), ("CARRIER", "Перевозчик")],
                default="CARRIER",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(
                fields=["initiator", "is_active"], name="offers_offe_initiat_306da5_idx"
            ),
        ),
    ]
