# Generated by Django 4.2.23 on 2025-12-09 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("offers", "0004_alter_offer_price_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="logistic",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "LOGISTIC"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logistic_offers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
