# Generated by Django 4.2.23 on 2025-12-10 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("offers", "0005_offer_logistic"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="accepted_by_logistic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="offer",
            name="intermediary",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "LOGISTIC"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="intermediary_offers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="initiator",
            field=models.CharField(
                choices=[
                    ("CUSTOMER", "Заказчик"),
                    ("CARRIER", "Перевозчик"),
                    ("LOGISTIC", "Логист"),
                ],
                default="CARRIER",
                max_length=16,
            ),
        ),
    ]
