# Generated by Django 4.2.23 on 2025-12-10 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("offers", "0006_offer_accepted_by_logistic_offer_intermediary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="carrier",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "CARRIER"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
