# Generated by Django 4.2.23 on 2025-12-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0007_alter_offer_carrier"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="deal_type",
            field=models.CharField(
                choices=[
                    ("customer_carrier", "Customer Carrier"),
                    ("logistic_carrier", "Logistic Carrier"),
                    ("customer_logistic", "Customer Logistic"),
                    ("logistic_logistic", "Logistic Logistic"),
                ],
                default="customer_carrier",
                max_length=32,
            ),
            preserve_default=False,
        ),
    ]
