# Generated by Django 4.2.23 on 2025-12-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0008_offer_deal_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="is_counter",
            field=models.BooleanField(default=False),
        ),
    ]
