# Generated by Django 4.2.23 on 2025-12-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0009_offer_is_counter"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="response_status",
            field=models.CharField(blank=True, default="", max_length=32, null=True),
        ),
    ]
