# Generated by Django 4.2.23 on 2025-12-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0010_offer_response_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("cashless", "Безналичный расчёт")],
                default="cash",
                max_length=20,
            ),
        ),
    ]
