# Generated by Django 4.2.23 on 2025-12-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0012_offerstatuslog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличные"),
                    ("cashless", "Безналичный расчёт"),
                    ("both", "Наличные + перечисление"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
    ]
