# Generated by Django 4.2.23 on 2026-01-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0013_alter_offer_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="driver_currency",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="offer",
            name="driver_payment_method",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="offer",
            name="driver_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
