# Generated by Django 4.2.23 on 2025-08-23 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("origin_address", models.CharField(max_length=255)),
                ("origin_city", models.CharField(max_length=100)),
                ("destination_address", models.CharField(max_length=255)),
                ("destination_city", models.CharField(max_length=100)),
                ("load_date", models.DateField()),
                ("delivery_date", models.DateField(blank=True, null=True)),
                (
                    "transport_type",
                    models.CharField(
                        choices=[
                            ("TENT", "Тент"),
                            ("CONT", "Контейнер"),
                            ("REEFER", "Рефрижератор"),
                            ("DUMP", "Самосвал"),
                            ("CARTR", "Автотранспортер"),
                            ("GRAIN", "Зерновоз"),
                            ("CRANE", "Кран"),
                            ("LOG", "Лесовоз"),
                            ("PICKUP", "Пикап"),
                            ("CEM", "Цементовоз"),
                            ("TANK", "Автоцистерна"),
                            ("MEGA", "Мега фура"),
                        ],
                        max_length=10,
                    ),
                ),
                ("weight_kg", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "price_value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "price_currency",
                    models.CharField(
                        choices=[
                            ("UZS", "сум"),
                            ("KZT", "тнг"),
                            ("RUB", "руб"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                        ],
                        default="UZS",
                        max_length=3,
                    ),
                ),
                (
                    "contact_pref",
                    models.CharField(
                        choices=[("email", "Email"), ("phone", "Телефон"), ("both", "Оба")],
                        max_length=10,
                    ),
                ),
                ("is_hidden", models.BooleanField(default=False)),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            ("pending", "На модерации"),
                            ("approved", "Одобрено"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("refreshed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("POSTED", "Опубликована"),
                            ("MATCHED", "В работе"),
                            ("DELIVERED", "Доставлено"),
                            ("COMPLETED", "Завершено"),
                        ],
                        default="POSTED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["moderation_status", "transport_type", "load_date"],
                        name="loads_cargo_moderat_194189_idx",
                    ),
                    models.Index(
                        fields=["origin_city", "destination_city"],
                        name="loads_cargo_origin__d2c5af_idx",
                    ),
                    models.Index(fields=["is_hidden"], name="loads_cargo_is_hidd_413b6e_idx"),
                ],
            },
        ),
    ]
