# Generated by Django 4.2.23 on 2025-08-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loads", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cargo",
            old_name="title",
            new_name="product",
        ),
        migrations.RemoveField(
            model_name="cargo",
            name="price_currency",
        ),
        migrations.AlterField(
            model_name="cargo",
            name="transport_type",
            field=models.CharField(
                choices=[
                    ("TENT", "Тент"),
                    ("CONT", "Контейнер"),
                    ("REEFER", "Рефрижератор"),
                    ("DUMP", "Самосвал"),
                    ("CARTR", "Автотранспортер"),
                    ("GRAIN", "Зерновоз"),
                    ("LOG", "Лесовоз"),
                    ("PICKUP", "Пикап"),
                    ("MEGA", "Мега фура"),
                    ("OTHER", "Другое"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(fields=["status"], name="loads_cargo_status_e392fa_idx"),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(fields=["refreshed_at"], name="loads_cargo_refresh_64fdaf_idx"),
        ),
    ]
