# Generated by Django 4.2.23 on 2025-08-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loads", "0002_rename_title_cargo_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="price_currency",
            field=models.CharField(
                choices=[
                    ("UZS", "сум"),
                    ("KZT", "тнг"),
                    ("RUB", "руб"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                ],
                default="UZS",
                max_length=3,
            ),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(fields=["price_value"], name="loads_cargo_price_v_72b7fb_idx"),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(fields=["price_currency"], name="loads_cargo_price_c_e7eaf2_idx"),
        ),
    ]
