# Generated by Django 4.2.23 on 2025-09-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loads", "0005_cargo_assigned_carrier_cargo_chosen_offer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="route_duration_min_cached",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cargo",
            name="route_km_cached",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
