# Generated by Django 4.2.23 on 2025-10-20 13:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("loads", "0007_cargo_price_uzs_cargo_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
