# Generated by Django 4.2.23 on 2025-11-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loads", "0009_cargo_axles_cargo_volume_m3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("transfer", "Перечисление"),
                    ("cash", "Наличными"),
                    ("both", "Оба варианта"),
                ],
                default="transfer",
                max_length=10,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
