# Generated by Django 4.2.23 on 2025-11-28 12:12

import api.loads.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("loads", "0011_cargo_destination_city_latin_cargo_origin_city_latin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoadInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField(default=api.loads.models.invite_expiry)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "load",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="loads.cargo",
                    ),
                ),
            ],
        ),
    ]
