# Generated by Django 4.2.23 on 2025-12-05 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("loads", "0013_loadinvite_created_by"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cargo",
            name="loads_cargo_is_hidd_413b6e_idx",
        ),
        migrations.RemoveField(
            model_name="cargo",
            name="is_hidden",
        ),
        migrations.AddField(
            model_name="cargo",
            name="hidden_for",
            field=models.ManyToManyField(
                blank=True,
                related_name="hidden_cargos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Скрыто для",
            ),
        ),
    ]
