# Generated by Django 4.2.23 on 2025-12-05 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("loads", "0014_remove_cargo_loads_cargo_is_hidd_413b6e_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cargos_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создано логистом",
            ),
        ),
    ]
