# Generated by Django 4.2.23 on 2025-12-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loads", "0016_alter_cargo_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cargo",
            name="hidden_for",
        ),
        migrations.AddField(
            model_name="cargo",
            name="is_hidden",
            field=models.BooleanField(default=False, verbose_name="Скрыта от других пользователей"),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="status",
            field=models.CharField(
                choices=[
                    ("POSTED", "Опубликована"),
                    ("MATCHED", "В работе"),
                    ("DELIVERED", "Доставлено"),
                    ("COMPLETED", "Завершено"),
                    ("CANCELLED", "Отменена"),
                ],
                default="POSTED",
                max_length=20,
            ),
        ),
    ]
