# Generated by Django 4.2.23 on 2025-12-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loads", "0017_remove_cargo_hidden_for_cargo_is_hidden_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("cashless", "Безналичный расчёт")],
                default="cash",
                max_length=10,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
