# Generated by Django 4.2.23 on 2025-12-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loads", "0018_alter_cargo_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличные"),
                    ("cashless", "Безналичный расчёт"),
                    ("both", "Наличные + безналичный расчёт"),
                ],
                default="cash",
                max_length=10,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
