# Generated by Django 4.2.23 on 2025-12-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loads", "0019_alter_cargo_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("pending", "На модерации"),
                    ("approved", "Одобрено"),
                    ("rejected", "Отклонено"),
                ],
                default="approved",
                max_length=10,
            ),
        ),
    ]
