# Generated by Django 4.2.23 on 2026-02-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loads", "0020_alter_cargo_moderation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="price_currency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("UZS", "сум"),
                    ("KZT", "тнг"),
                    ("RUB", "руб"),
                    ("USD", "USD"),
                    ("EUR", "EUR"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
