# Generated by Django 4.2.23 on 2026-02-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loads", "0021_alter_cargo_price_currency"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cargo",
            name="loads_cargo_moderat_194189_idx",
        ),
        migrations.RemoveIndex(
            model_name="cargo",
            name="loads_cargo_origin__d2c5af_idx",
        ),
        migrations.RemoveIndex(
            model_name="cargo",
            name="loads_cargo_status_e392fa_idx",
        ),
        migrations.RemoveIndex(
            model_name="cargo",
            name="loads_cargo_refresh_64fdaf_idx",
        ),
        migrations.RemoveIndex(
            model_name="cargo",
            name="loads_cargo_price_v_72b7fb_idx",
        ),
        migrations.RemoveIndex(
            model_name="cargo",
            name="loads_cargo_price_c_e7eaf2_idx",
        ),
        migrations.RemoveIndex(
            model_name="cargo",
            name="loads_cargo_origin__ed5071_idx",
        ),
        migrations.RemoveIndex(
            model_name="cargo",
            name="loads_cargo_destina_ac8eec_idx",
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(
                fields=["moderation_status", "is_hidden", "status", "load_date"],
                name="cargo_main_filter",
            ),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(
                fields=["status", "load_date", "transport_type"], name="cargo_status_load"
            ),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(
                fields=["customer", "status", "created_at"], name="cargo_customer_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(
                fields=["created_by", "status", "created_at"], name="cargo_created_by_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(
                fields=["origin_city_latin", "destination_city_latin"],
                name="loads_cargo_origin__c04aea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(fields=["-refreshed_at", "-created_at"], name="cargo_refresh_sort"),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(fields=["price_uzs", "load_date"], name="cargo_price_idx"),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(fields=["weight_kg"], name="cargo_weight_idx"),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(fields=["transport_type", "load_date"], name="cargo_transport_idx"),
        ),
    ]
