# Generated by Django 4.2.23 on 2026-03-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loads", "0022_remove_cargo_loads_cargo_moderat_194189_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="cargo_category",
            field=models.CharField(
                choices=[
                    ("FOOD", "Продукты питания"),
                    ("FMCG", "Повседневные товары"),
                    ("TEXTILE", "Текстиль"),
                    ("APPLIANCES", "Бытовая техника"),
                    ("FURNITURE", "Мебель"),
                    ("BUILDING", "Стройматериалы"),
                    ("METALLURGY", "Металлургия"),
                    ("SPARE_PARTS", "Запчасти"),
                    ("PHARMA", "Фармацевтика"),
                    ("CHEMICAL", "Химическая промышленность"),
                    ("ROAD_CONSTRUCTION", "Дорожное строительство"),
                    ("MINERALS", "Минералы"),
                    ("WASTE", "Отходы"),
                    ("CARS", "Автомобили"),
                    ("OTHER", "Другое"),
                ],
                default="OTHER",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="product",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="Название груза"
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="transport_type",
            field=models.CharField(
                choices=[
                    ("TENT", "Тент"),
                    ("CONT", "Контейнер"),
                    ("REEFER", "Рефрижератор"),
                    ("DUMP", "Самосвал"),
                    ("CARTR", "Автотранспортер"),
                    ("MEGA", "Мега фура"),
                    ("OTHER", "Другое"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cargo",
            name="weight_kg",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(fields=["cargo_category"], name="cargo_category_idx"),
        ),
    ]
