# Generated by Django 4.2.23 on 2026-04-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loads", "0023_cargo_cargo_category_alter_cargo_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargo",
            name="destination_region",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="cargo",
            name="origin_region",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
