# Generated by Django 4.2.23 on 2025-12-13 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("agreements", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="agreement",
            name="agreements__status_8c716b_idx",
        ),
    ]
