# Generated by Django 4.2.23 on 2025-12-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agreements", "0002_remove_agreement_agreements__status_8c716b_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="carrier_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="agreement",
            name="carrier_full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="agreement",
            name="carrier_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="carrier_phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="agreement",
            name="carrier_registered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="customer_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="agreement",
            name="customer_full_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="agreement",
            name="customer_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="customer_phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="agreement",
            name="customer_registered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="logistic_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="agreement",
            name="logistic_full_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="agreement",
            name="logistic_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="logistic_phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="agreement",
            name="logistic_registered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
