# Generated by Django 4.2.23 on 2025-08-21 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailotp",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="emailotp",
            name="attempts_left",
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="emailotp",
            name="expires_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emailotp",
            name="purpose",
            field=models.CharField(
                choices=[("verify", "verify"), ("reset", "reset")], default="verify", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="emailotp",
            index=models.Index(
                fields=["user", "purpose", "-created_at"], name="accounts_em_user_id_dc4b02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailotp",
            index=models.Index(
                fields=["purpose", "is_used"], name="accounts_em_purpose_16df0a_idx"
            ),
        ),
    ]
