# Generated by Django 4.2.23 on 2025-11-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_phoneotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fcm_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("LOGISTIC", "Логист"),
                    ("CUSTOMER", "Заказчик"),
                    ("CARRIER", "Перевозчик"),
                ],
                default="CUSTOMER",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="profile",
            constraint=models.UniqueConstraint(fields=("user",), name="unique_profile_user"),
        ),
    ]
