# Generated by Django 4.2.23 on 2025-12-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_user_fcm_token_alter_user_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_accept_policy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="policy_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
