# Generated by Django 4.2.23 on 2026-01-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cancelled_orders_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Количество заказов, отменённых пользователем"
            ),
        ),
    ]
