# Generated by Django 4.2.23 on 2026-02-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_profile_cancelled_orders_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_seen",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
