# Generated by Django 4.2.23 on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_alter_user_photo_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="inn",
            field=models.CharField(blank=True, max_length=32, verbose_name="ИНН"),
        ),
        migrations.AddField(
            model_name="user",
            name="legal_address",
            field=models.CharField(blank=True, max_length=500, verbose_name="Юридический адрес"),
        ),
    ]
