# Generated by Django 4.2.30 on 2026-06-30 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_fleetmembership'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fleetmembership',
            new_name='accounts_fl_owner_i_c37d14_idx',
            old_name='accounts_fl_owner__3f31d6_idx',
        ),
        migrations.RenameIndex(
            model_name='fleetmembership',
            new_name='accounts_fl_member__0007fc_idx',
            old_name='accounts_fl_member__d14f44_idx',
        ),
    ]
